### ISSUE TITLE
Vibrate does not work when vibrate only (no sound) is selected

### ISSUE THREAD

**Issue by hyzenth** [SimpleMobileTools/Simple-Clock#189]
Android v9
Software vG850UM10o
Model LM-G850UM

**Comment by tibbi** [comment]
at which app function (tab)?

**Comment by hyzenth** [comment]
The Clock tab.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by hyzenth** [comment]
Sorry, no.  It always says "Clock" in the upper left - I thought it was identifying the tab I was in jut now :/

It's the alarm clock tab. The second from the left.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tibbi** [comment]
should work in 5.7.0

**Comment by ShamrockLee** [comment]
The same issue occur on version 5.10.0 from F-Droid on Volla Phone 22 (11.1-20230111-STABLE-mimameid, Android 11, Linux 4.14.186-g3813583ccf55
#18 Sat Dec 24 08:35:38 CET 2022, microG Service Core 0.2.27.22316).

Default alarm set to system default alarm. The volume mode is the normal one (ring upon phone calls).

Reproduction steps:

1.  Add an alarm instance.
2.  Select alarm from System Sounds as "No sound".
3.  Check the "Vibrate" checkbox.
4.  Turn off the screen by short-pressing the power button once. This step is needed to reproduce this issue.

Actual behavior: The alarm screen appers without any vibration.

Expected behavior: Vibrate with no alarm.

@tibbi Should I open a new issue?

**Comment by ShamrockLee** [comment]
It turns out that the alarm doesn't vibrate at all when the screen is locked, regardless of the choice of the sound.

I'll open a new issue.
