### ISSUE TITLE
Add more count down timers

### ISSUE THREAD

**Issue by morfikov** [SimpleMobileTools/Simple-Clock#28]
For now you can add only one count down timer. It would be nice to add more timers so they could count down to different events. Also the timers should have labels, and the position of the timers on the list shouldn't be fixed. It's optional to have each event different alarm settings.

**Comment by vsudakov** [comment]
yeah, this is must-have-feature
=)

**Comment by malnvenshorn** [comment]
Yes I agree, adding multiple timers would be a great feature.

**Comment by GR412** [comment]
I would also like to see this.

**Comment by ltGuillaume** [comment]
Same.

**Comment by anishmittal2020** [comment]
Please add this feature. Custom timers are quite important for me. It would be great if we could create a lot of such timers, that I could.

**Comment by madb1lly** [comment]
Hi @tibbi,
First, thanks for all the apps you make, they're a great contribution to the FLOSS community of Android apps.

Just to add that this is the only reason I'm not using your clock app at the moment is that it doesn't support multiple timers, which is a useful function for me.

Cheers 🙂

**Comment by shanemd** [comment]
Echoing @madb1lly. I use multiple timers on a daily basis, and this is the one reason I haven't switched to this app.

To provide a concrete example of use: Cooking. Frequently there are multiple dishes that are done at different times, and need separate timers to track them. I also like to leave a few timers 'on deck' for when I need them. Cooking rice? There's already a 15 minute timer filled out and labeled 'rice'. Just open the app and press 'start'!

Thank you for these wonderful apps. The simplicity is very much appreciated. I'm sure it's challenging to find the balance with all these compelling feature requests.

Let me know if there's anything I can do to help with this one. 

Cheers

**Comment by TomFernandes** [comment]
Especially as long as one can only input time by spinner (#68) it is too much of a hassle to use the timer. With  multiple timers to choose from one would not have to use the tedious spinner so often.

**Comment by DoctorSubtilis** [comment]
+1 feature very important

**Comment by ltGuillaume** [comment]
...and please, if you arrive at implementing this, please make it a normal list, so that all timers can be seen at once, instead of the ridiculous implementation of the default Clock where you can only see one timer at a time and have to "scroll" through every individual one to find the one with a pre-set time.

![image](https://user-images.githubusercontent.com/4777345/114269514-0f717e00-99f7-11eb-877c-0bc0ccd83b2f.png)

Honestly, there is so much wrong with the default Clock app's UX, it's ridiculous. [Clock+](https://f-droid.org/en/packages/com.philliphsu.clock2/) and to some extent [Alarmio](https://play.google.com/store/apps/details?id=me.jfenn.alarmio) have the best interface, which includes far more intuitive time pickers than Android's, but both of them are not to be used on Android 10+ if you actually want to be woken by them.

**Comment by ReznoRMichael** [comment]
Hello,
I just wish you to know that this app is currently the only clock/timer app on Android that caught my eye. It's so simple, clear. No fancy cheap looks, just pure modern aesthethic simplicity. No ads. Fast response time. It reminds me so much of the default Clock app for Windows Mobile 10, which I still miss so dearly!

There is still one last feature, that I greatly miss and is incredibly useful: **Adding more timers (with own labels).** The same like on Clocks and Alarms tabs, but for Timers. Then your app will be just perfect 💚 Please add this, I beg you. Default Android apps, Google app and Huawei app doesn't have this. It is a great niche to fill.

Thank you, and you've done a really great job on all those simple apps!
Have a great day,
Michael
![wp_ss_20210524_0001-s](https://user-images.githubusercontent.com/27960356/119402707-99428580-bcdd-11eb-8c0f-ab42637faa4f.png)

**Comment by tibbi** [comment]
will be added in 5.6.0

**Comment by Ian2020** [comment]
Love this new feature, thank you!

**Comment by shanemd** [comment]
:raised_hands:
