### ISSUE TITLE
Alarm sometimes doesn't appear on lock Screen

### ISSUE THREAD

**Issue by Git08hb** [SimpleMobileTools/Simple-Clock#387]

**Comment by Git08hb** [comment]
When my alarm goes on i have to type my password sometimes in order to access the app

**Comment by tibbi** [comment]
what app and OS version are you using? Can you reproduce it reliably?

**Comment by Git08hb** [comment]
Simple Clock (5.8.1 F-Droid)

Android 11

**Comment by tschlegeldigos** [comment]
I can confirm this behavior, but a little different.
When the screen is locked, the alarm isn't going off at all. It only starts, when I activate the screen, then it's showing the current time instead of the ringing time. I disabled all optimisation and permission removal options for Simple Clock.

Simple Clock 5.9.2
Android 12

**Comment by farline99** [comment]
I am also affected by this problem. Usually alarm auto disables when I unlock phone 🤪

**Comment by basings** [comment]
You have to unlock the phone first before you can turn off an alarm which is annoying. 

Alarm is not automatically disabled once the phone is unlocked.

- GrapheneOS Android 13
- v 5.10.0

**Comment by tibbi** [comment]
did it happen again?

**Comment by Git08hb** [comment]
Nope sorry this was by accident
