### ISSUE TITLE
Sounds bugs

### ISSUE THREAD

**Issue by Git08hb** [SimpleMobileTools/Simple-Clock#392]
1. I set my alarm to no sound and just vibrating however the system sound started instead of just vibrating.

2. When set my own sound it will play the system sound and my own sound at the same time.

Simple Clock 5.8.1 (F-Droid)

Samsung A51 Android 11

**Comment by tibbi** [comment]
That is an old app version, retry with 5.9.2 please

**Comment by Git08hb** [comment]
I updated the F-Droid version of this app (5.9.1) and the bugs didn't get fixed

**Comment by Sieger14** [comment]
Same issue

Simple Clock 5.9.3
F-Droid 1.15.2
Android 10
Crosscall Core-X4

**Comment by gri38** [comment]
Hello: O habe the same issue (system sound + alarm sound are played at the same time).
I ended to uninstall the app.
I'm tracking this bug, if it's closed I'come back again.

**Comment by cofi89** [comment]
Seems that disabling "Allow playing sound" in Notification Settings fixes the second issue (playing both the user and system sound simultaneously). Quick tests at least confirm it.  

Haven't tested the first issue, however with vibrate + user sound set, if the screen is unlocked, alarm only vibrates, same as in #405.

Redmi Note 10S with MIUI 13/Android 12, Simple Clock 5.10.0 (f-droid).

**Comment by gri38** [comment]
Hi.
I've just reinstalled the app. 
Indeed, disabling "sound and vibration" (on my android version it's "sound and vibration") seems to solve issue 2.
Thanks. 
Maybe you could code a screen displayed only the first time the user opens this app after installing to explain that. And a question mark button somewhere to popup this explication...

N.b.: for me issue 2 is not the system sound is played: when 2 alarms are set, both sounds rings for an alarm.

Thanks!!!

**Comment by Lagile** [comment]
Hello,
I hope I'll be clear, as English is not my mother tongue!

I have the same issue (chosen alarm + system alarm playing together) on my new mobile phone (Motorola Moto G51, Android 12), but everything is fine on my previous one (Energizer P600S, Android 7.1) with the 5.10.0 version of the app on both phones. The bug happens when the phone is on standby. If the phone is on, only one sound is played.

To solve the double ringing, I modified the settings like this:
— open Simple-Clock settings (photo 1)
— select Notifications, where all the alarms and countdowns are listed (photo 2)
— select one of the alarms (photo 3) to see details
— choose default alarm on the list (photo 4). Repeat for each alarm and countdown.

![1- Horloge](https://user-images.githubusercontent.com/34857846/211521607-a3a2fff2-312f-4651-bbe9-c1d28cbd6c5d.png)
![2-](https://user-images.githubusercontent.com/34857846/211521619-4f58c51e-7833-451a-aac3-8de05e1b9fac.png)
![3-](https://user-images.githubusercontent.com/34857846/211521622-84ca2406-a381-4586-a439-50ca8ec1da13.png)
![4-](https://user-images.githubusercontent.com/34857846/211521627-39ffc6fc-bc1a-4db6-a762-ce536b1a94fb.png)

I hope it can help other people, and maybe solving the issue more easily. :-)

**Comment by val9299** [comment]
I've also sound & vibration issues with Simple Clock 5.10.0 (GitHub), Android 13, Oppo A77.

Clock sound issues:
- It always starts with the standard sound, no matter if another/no sound was chosen
-> if another sound was chosen, it will play both at the same time first, then it changes to the chosen sound only
-> if no sound was chosen, it will play a few seconds of the standard sound before turning off the sound
- Vibration does not work when enabled, also while having vibrations enabled on my Android settings

Timer sounds work perfectly fine (Clock sounds should do exactly this as well)

Timer vibration issue
- Vibration does not work when enabled, also while having vibrations enabled on my Android settings

**Comment by val9299** [comment]
@Lagile, thank you! At first I had difficulties to understand the instructions, but now I got them and it works. They prevent having two alarm sounds at the same time. I've added English screenshots, so it might be easier understandable.
![Screenshot_2023-01-17-22-12-48-21_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/53229616/213026139-69f0a9bd-a89b-4a41-8f41-f05a34cb36aa.jpg)
![Screenshot_2023-01-17-22-14-02-46_8142442b4340f41fb3bd44535ad8f76b](https://user-images.githubusercontent.com/53229616/213026144-8f5a3d81-c198-45ed-8abe-592aa6e666fc.jpg)
![Screenshot_2023-01-17-22-14-44-67_8142442b4340f41fb3bd44535ad8f76b](https://user-images.githubusercontent.com/53229616/213026149-7ee8d362-022c-4361-ab56-65059ec5ee05.jpg)

**Comment by val9299** [comment]
@Lagile, thank you! At first I had difficulties to understand the instructions, but now I got them and they work. I've added English screenshots because they might be more comprehensible for a bigger audience. 

This setting prevents issue 2 of the initial report. Hence, only one alarm sound will be played, not two at the same time.

![Screenshot_2023-01-17-23-22-58-04_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/53229616/213034724-490d1d2d-e43b-43fb-a27a-c3960e03413a.jpg)
![Screenshot_2023-01-17-23-24-38-71_8142442b4340f41fb3bd44535ad8f76b](https://user-images.githubusercontent.com/53229616/213034728-78cfd5a7-f6fa-47f8-b77f-6600a0f6da99.jpg)
![Screenshot_2023-01-17-23-25-19-96_8142442b4340f41fb3bd44535ad8f76b](https://user-images.githubusercontent.com/53229616/213034731-a065e10a-59c9-4280-87f0-5493c93b6aca.jpg)
