### ISSUE TITLE
alarm stops when smartphone is horizontal

### ISSUE THREAD

**Issue by TheRupp** [SimpleMobileTools/Simple-Clock#533]
Hello,

if I rotate my smartphone from vertical/portrait to horizontal/landscape while the alarm is ringing, then the alarm stops ringing immediately and the app immediately disappears from the screen.

If my smartphone is held horizontally before the alarm rings, then the alarm rings very shortly (less than 1 second) before it stops and the app immediately disappears from the screen.

(This alarm does not ring again after a few minutes like snoozing.)

This problem has only happened recently, maybe since roughly two weeks. I can't remember how long exactly. This problem didn't exist before that time.

my smartphone = Fairphone 3+
Android version = 13 (Android security update: 5 August 2023) (Google Play system update: 1 July 2023) (Kernel version: 4.9.337-perf+) (Build number: 6.A.020.0)
app version = 5.11.2

**Comment by Moonay-TeamCoffee** [comment]
Hello,

I've also had the same problem since Version 5.11.1

If the phone is in Portrait mode at the time the alarm: it works proper,
But if in Landscape, then the screen lights up, the alarm clock appears for a fraction of a second, and then turn off without making a sound.

I recorder that behaviour in this video : https://www.mediafire.com/file/w8bwy0n6mk84asv/SimpleToolsClockLandscapeBug.mp4/file

Phone : Samsung Galaxy S10+
OS : Android 12

**Comment by Moonay-TeamCoffee** [comment]
Hello.

This issue had been called a while ago, but has not been fixed, since no update has been released to the Fdroid repository, I've been stuck with the version of the app with the problem (5.11.2)
Can the latest fixes be please published in a new version soon ?
