### ISSUE TITLE
Mass adding alarms

### ISSUE THREAD

**Issue by sz3lbi** [SimpleMobileTools/Simple-Clock#79]
Hi. I desperately look for any clock/alarm app which will allow me to add alarms en masse for example in form of text like:
``01.08.2018;12:00;description
02.08.2018;13:00;another description``
Is that possible for you to add that feature to this app? I would love it, I won't lie.

**Comment by Amunratis** [comment]
Hullo, I would like to add this feature however I am having issues compiling the repo. What version of Android Studio are you using @tibbi  ?  

/root/AndroidStudioProjects/Simple-Clock/app/src/main/kotlin/com/simplemobiletools/clock/activities/MainActivity.kt: (136, 30): Type mismatch: inferred type is ViewPagerAdapter but PagerAdapter? was expected

/root/AndroidStudioProjects/Simple-Clock/app/src/main/kotlin/com/simplemobiletools/clock/activities/MainActivity.kt: (137, 20): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
public fun ViewPager.onPageChangeListener(pageChangedAction: (newPosition: Int) -> Unit): Unit defined in com.simplemobiletools.commons.extensions

/root/AndroidStudioProjects/Simple-Clock/app/src/main/kotlin/com/simplemobiletools/clock/activities/MainActivity.kt: (138, 39): Unresolved reference: it

> Task :app:buildInfoGeneratorDebug

What I tried so far: 
*setting the propper kotlin version
*changing the embeded openjdk for oracle jdk
*placing the kotlin dependency in gradle.app
*Invalidate/restart caches
*Reinstalling my whole system

I am working on the Android Studio 3.3.2

**Comment by tibbi** [comment]
Im just updating older apps, you should be able to build it tomorrow or so

**Comment by Amunratis** [comment]
Thank you ever so kindly ^.^

**Comment by tibbi** [comment]
this isnt on the roadmap
